### ISSUE TITLE
New Meme Image

### ISSUE THREAD

**Issue by Deemitry88** [Discord-Oxygen/Discord-Oxygen#29]
It's not an Issue but I did your meme in better quality, here :

High Quality (1920x2160) :
![image](https://user-images.githubusercontent.com/91915462/187090116-95d9fd68-3024-40ce-86aa-3003fac7bd2d.png)

Low Quality (465x523) :
![image](https://user-images.githubusercontent.com/91915462/187090228-bc4c775d-1577-4851-a539-9433f744ce88.png)

**Comment by hxr404** [comment]
thanks, fixed it (although a bit late :D)

(I kinda forgot about this and marked it as read lol)
